name: Release Bot

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = context.payload.ref.replace('refs/tags/', '');

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: version,
              name: `Release ${version}`,
              body: `New release for version ${version}`,
            });
