name: Welcome Bot

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome all contributors
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const login = context.payload.sender.login;
            const type = context.eventName === 'issues' ? 'issue' : 'pull_request';
            const number = context.payload[type].number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body: `👋 Hey @${login}, thanks for your ${type.replace('_', ' ')}! We appreciate your contribution. 🚀`
            });

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              labels: ['greeting']
            });
