name: Welcome Bot

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome first-time contributors
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const login = context.payload.sender.login;
            const type = context.eventName === 'issues' ? 'issue' : 'pull_request';

            const listPRs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });

            const listIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });

            const isFirstPR = listPRs.data.filter(pr => pr.user.login === login).length === 1;
            const isFirstIssue = listIssues.data.filter(issue => issue.user.login === login).length === 1;

            if ((type === 'issue' && isFirstIssue) || (type === 'pull_request' && isFirstPR)) {
              const number = context.payload[type].number;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                body: `👋 Welcome @${login}! Thanks for your first ${type.replace('_', ' ')}. We’re glad you’re here! 🎉`


              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                labels: ['wontfix']
              });    
            }
